### ISSUE TITLE
Images not available anymore

### ISSUE THREAD

**Issue by GTuritto** [nickcernis/outpost#1]
When executing Vagrant Up I am receiving the following error:
```
==> default: Box 'nickcernis/outpost' could not be found. Attempting to find and install...
    default: Box Provider: vmware_desktop, vmware_fusion, vmware_workstation
    default: Box Version: >= 0
==> default: Loading metadata for box 'nickcernis/outpost'
    default: URL: https://atlas.hashicorp.com/nickcernis/outpost
==> default: Adding box 'nickcernis/outpost' (v0.2.1) for provider: vmware_desktop
    default: Downloading: https://atlas.hashicorp.com/nickcernis/boxes/outpost/versions/0.2.1/providers/vmware_desktop.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 500 Internal Server Error
```

I went to that URL and it seems the author is not maintaining the project anymore and the images have been removed. If I am able to get the original images I will try to bring this project back to life.

**Comment by nickcernis** [comment]
Hi, @GTuritto. I removed the image due to low demand – sorry for the inconvenience there. The image was built from the Packer config here: https://github.com/nickcernis/outpost-packer

I'm in two minds as to whether to continue work on Outpost, since [VVV](https://github.com/Varying-Vagrant-Vagrants/VVV) and alternatives have higher adoption. I've also been looking at Docker as a lighter weight alternative to build WP dev environments, so may rethink the direction I'm taking with it.

If you've been using Outpost or have any opinions about the future of the project, please feel free to share them.

**Comment by GTuritto** [comment]
Yes I have tested VVV I was using Outpost up to 1 year ago and I really liked some of your functionality also at that time VVV has no good support for VMware-Fusion (what I prefer instead of Parallels). Agree Docker is very lightweight, but on OSX requires to use a Virtual Image of a Linux version with support for docker. 

I think your project was really nice and I considered somehow better than VVV. Will try to give a try to use packer (never done an image from scratch), in meantime I will try VVV for my urgent need of a local development environment (not that I do much development with Wordpress , but sometimes I need to ).

Thank You and good luck.

**Comment by nickcernis** [comment]
Thanks for your feedback on this, @GTuritto.

I relaunched Outpost as a Docker-based template: http://outpost.rocks/. If you use Docker for Mac, no Virtual Box/VMware is required.

I still have more work to do to the base install, but it's already building and running faster than the previous Vagrant/VMware solution for me. I'll work to add more info later.

The new repo is at: https://github.com/nickcernis/outpost-docker
